hachiojipm/awesome-perl

README.md

Motivation
--
Data driven testing framework is useful at different situations in a variety of contexts.
It provides simple and smart way to write test cases that are led by data.
Situation
--
Lots of modules depends them;
- https://metacpan.org/requires/module/Test::Base?sort=[[2%2C1]]&p=1&size=500
- https://metacpan.org/requires/module/Test::Base::Less?sort=[[2%2C1]]&p=1&size=500

Add Test::Base family

---

README.md

A range of suggestions with their own comments

Various Suggestions

---

README.md

Minor grammar and punctuation changes too.

Fix URLs and link names

---

README.md

wrong module name and link is fixed.

fixed typo(Test::MockTime)

---

README.md

Form Frameworks, Web Framework-like libraries and some popular template libraries

A wide range of new libraries

---

README.md

Added perlmaven.com list
Added some REST frameworks
Added put Moose, Mouse, Moo and Mo in order from big->tiny
Added DOCSIS::ConfigFile

Yet more suggestions

---

README.md

Motivation
--
THis is really fast Plack handler, please see bellow.
http://kazeburo.hatenablog.com/entry/2014/11/14/173423
Moreover it is production quality.

Add Gazelle which is a high performance PSGI/Plack server

---

README.md

add useful tools

---

README.md

Hi,
Tell me if someone wants to arrange this new modules in a other order.
Best regards.
Jean-Marie

Adding some modules

---

README.md

Some suggestions for manipulating lists (arrays)

Add List Manipulation suggestions

---

README.md

Also put sections in alphabetical order

Fix anchor link to devops-tools

---

README.md

Added databases and Event Loops

---

README.md

Tests pass better, although still not perfect.
Added DBD::CSV, Text::CSV*, HTML::Template, Net::DNS, Net::RabbitMQ, and Net::STOMP

Fix tests and add additional modules

---

README.md

I also made new section (Web Scraping) which was surprisingly not exist.

Added Chart::Clicker, Resque, and Web::Scraper

---

README.md

found this list a while ago and found it to be done well, fit for linking from wherever possible, including awesome-perl - I think

link to srezic's curated module list

---

README.md

Adding https://metacpan.org/pod/HTML::FormHandler because it's awesome :-)

Add HTML::FormHandler

---

README.md

Fix typos and add consistent header space.

---

README.md

Add Video and Audio sections, with some initial entries

Add Video and Audio sections

---

README.md

add Search::Elasticsearch

---

README.md

Many things related to caching via CHI

Add Caching section with many CHI things

---

README.md

As per the subject, no typo this time

Add Device section with some examples

---

README.md

The modules on the SSH section were not so awesome.
I have redone the section listing modern popular modules.

Redo SSH section

---

README.md

Commercial webservices and BSON

Add some new suggestions

---

README.md

Smart::Comments awesome debugging/development module. It provides
- object dumping/pretty-printing
- debugging "`print`s"
- assertions
- progress bars
- time remaining estimates
Originally authored by Damian Conway and described in his book, __Perl Best
Practices__

add Smart::Comments

---

README.md

Add pagerduty

---

README.md

Seems worth a mention, since it may eventually form the basis of the new OO system in a future Perl version

Include Object::Pad
